### ISSUE TITLE
User can discover a movie.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#1]
## 💰 Motivation

At the push of a button, user can discover a random movie to watch if they're having trouble deciding.

## 📐 Plan

Allow user to push a button, which will trigger a request for a movie from a movie database API, and will display the result to the user.

## ✅ Task List

- [x] Create HTML elements and CSS styling to complete the homepage. 
- [x] Using dummy data, create HTML elements and CSS styling to complete the page that displays the movie result.
- [x] Add an event listener to the 'discover' button on the homepage. 
- [x] Add a function that uses the http GET method to request movie data. 
- [x] Append the response to the movie result view.
- [x] Ensure that only one movie at a time is displayed. 
- [x] Create a function to find the year of the movie.
- [x] Create a variable containing genre data.
- [x] Create a function to find genres of the movie by sorting through their genre IDs.
- [x] Once everything is looking and functioning as intended, delete the dummy data. 
- [x] Add a button to the result page.
- [x] Add an event listener to the previously created button.
- [x] Add functionality to the button so that the GET method is triggered again.
- [x] Replace the previous movie result with the new result.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
