### ISSUE TITLE
User can filter results by rating.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#13]
## 💰 Motivation

User can filter the movie results by specifying a rating.

## 📐 Plan

Allow the user to input a specific rating. Then sort through the results so that only movies with the specified rating will display.

## ✅ Task List

- [x] Add a range input to the HTML form.
- [x] When the form is submitted, save the input value in a variable.
- [x] Clear the form.
- [x] Use the rating value variable to sort through the movie results.
- [x] Ensure that only movies with a matching rating will be displayed. 
- [x] Ensure that if a new rating is inputted, the results will be updated as well.
- [x] Ensure that if a year, a genre, and a rating are inputted, the results will cater to all three values.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
