### ISSUE TITLE
User can filter results by release year.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#2]
## 💰 Motivation

User can filter the movie results by specifying a release year.

## 📐 Plan

Allow the user to input a specific release year. Then sort through the results so that only movies with the specified year will display.

## ✅ Task List

- [x] Add a form to the homepage with a year input.
- [x] When the form is submitted, save the input value in a variable.
- [x] Clear the form.
- [x] Use the year value variable to sort through the movie results.
- [x] Ensure that only movies with a matching year will be displayed. 
- [x] Ensure that the home button on the nav-bar redirects to the homepage.
- [x] Ensure that if a new year value is inputted, the results will be updated as well.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
