### ISSUE TITLE
Convert to ES6

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#27]
## ✅ Task List

- [x] Convert all 'var' keywords to 'const' or 'let'.
- [x] Convert regular functions to arrow functions if appropriate.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
