### ISSUE TITLE
User can filter results by genre.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#3]
## 💰 Motivation

User can filter the movie results by specifying a genre.

## 📐 Plan

Allow the user to input a specific genre. Then sort through the results so that only movies with the specified genre will display.

## ✅ Task List

- [x] Add a genre input to the HTML form.
- [x] When the form is submitted, save the input value in a variable.
- [x] Clear the form.
- [x] Use the genre value variable to sort through the movie results.
- [x] Ensure that only movies with a matching genre will be displayed. 
- [x] Ensure that if a new genre is inputted, the results will be updated as well.
- [x] Ensure that if both a year and a genre are inputted, the results will cater to both values.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
