### ISSUE TITLE
User can add movie result to watchlist.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#4]
## 💰 Motivation

If a user comes across a movie they like, they can save it to a watchlist.

## 📐 Plan

Allow the user to click a button which will save the movie's data to be revisited later.

## ✅ Task List

- [x] Add an 'add to watchlist' button to the movie result view.
- [x] When each movie is added to the page, store the current movie's data.
- [x] Ensure that when a new movie appears, the 'current movie' data is updated to the new current movie.
- [x] Add an event listener to the 'add to watchlist' button for the click event.
- [x] When the 'add to watchlist' button is clicked, the current movie data should be added to the data model.
- [x] Ensure that the data model is saved to local storage.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
