### ISSUE TITLE
User can view watchlist.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#5]
## 💰 Motivation

After the user has saved a movie to their watchlist, they'll want to view the list.

## 📐 Plan

Display the watchlist.

## ✅ Task List

- [x] Create a new HTML view element which will contain the watchlist.
- [x] Add an event listener for the click event to the nav bar for the watchlist button.
- [x] Clicking the button should change the view to the watchlist view.
- [x] Ensure that the button matching the current view is underlined in the nav bar.
- [x] Add an event handler to the global window for the DOMContentLoaded event.
- [x] Use the 'render movie' function to create a DOM tree for the movies saved in local storage.
- [x] Query the HTML element that will contain the watchlist.
- [x] Append all saved movies in the data model to the watchlist.
- [x] Ensure that each new addition to the list is displayed and can be viewed in the watchlist without having to refresh the page.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
