### ISSUE TITLE
User can delete movie from watchlist.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/ajax-project#6]
## 💰 Motivation

After the user has watched a movie on their watchlist, they should be able to delete it.

## 📐 Plan

Add a delete functionality to every entry on the watchlist which the user will be able to utilize.

## ✅ Task List

- [x] Add a click target of a delete icon onto entries on the watchlist.
- [x] Create a delete confirmation modal.
- [x] When the delete icon is clicked, the modal should appear.
- [x] Exit the modal if the user clicks 'cancel' or if they click outside of the confirmation box.
- [x] Remove the entry from the data model and the entry's DOM tree if the user clicks delete.
- [x] Remove any unnecessary CSS styling. 
- [x] Test all functionality.
- [x] Fix all bugs and errors.
